---
title: "Example"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Guideline

- `###` : 예제 제목
- `####` : 학번 및 이름
- 그 아래는 자유롭게 구성 (설명 / 코드 / 그림 등)
- 아래 이미 생성되어 있는 예제처럼 작성하면 된다.

## Examples

### Vector Operations in R

#### 학번 : 21234567 / 이름 : 홍길동

이 예제를 포함하여, 다른 학생의 예제를 삭제하지 않음.
두 개의 벡터를 생성하고, dot product를 계산한다. 두 가지 방법으로 해 본다.


```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(5, 4, 3, 2, 1)
sum(x * y)
```
```{r}
t(x) %*% y
```


### 정렬 알고리즘

#### 학번: 22110681 / 이름: 이윤형

함수 기능을 이용하여 버블 정렬과 선택 정렬 알고리즘을 구현하였습니다.

```{r}
# 버블 정렬
bubble_sort <- function(x) {
  n <- length(x) 
  
  for (i in 1:(n - 1)) {
    for (j in 1:(n - i)) {
      if (x[j] > x[j + 1]) {
        tmp <- x[j]
        x[j] <- x[j + 1]
        x[j + 1] <- tmp
      }
    }
  }
  return(x)
}
vec1 <- c(5,7,1,6,4)
bubble_sort(vec1)
```
```{r}
# 선택 정렬
selection_sort <- function(x) {
  n <- length(x) 
  for (i in 1:(n - 1)) {
    min <- i
    for (j in (i + 1):n) {
      if (x[j] < x[min]) {
        min <- j
      }
    }
    
    if (min != i) {
      tmp <- x[i]
      x[i] <- x[min]
      x[min] <- tmp
    }
  }
  
  return(x)
}
vec2 <- c(7,4,2,6,1)
selection_sort(vec2)

```
